### ISSUE TITLE
yaf已安装 HTTP ERROR 500 

### ISSUE THREAD

**Issue by skyisboss** [yumufeng/thinkyaf#1]
请问一下如何正确安装并运行

**Comment by yumufeng** [comment]
yaf的安装参考：https://www.kancloud.cn/yumufeng/thinkyaf/554825

**Comment by yumufeng** [comment]
nginx的配置参照：https://github.com/yumufeng/thinkyaf/blob/master/yaf.conf  不需要启用pathinfo

**Comment by skyisboss** [comment]
> nginx的配置参照：https://github.com/yumufeng/thinkyaf/blob/master/yaf.conf 不需要启用pathinfo

感谢回复。yaf运行良好，但是thinkyaf一直没能跑起来  :(
